name: Trigger update workflow

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Extract sha
        id: extract
        shell: bash
        run: |
          echo "::set-output name=sha::$(sha=${{ github.sha }}; echo ${sha:0:6})"

      # - name: print token
      #   shell: bash
      #   run: |
      #     echo "$(${{ secrets.DISPATCH_TOKEN }} | sed -e 's/\(.\)/\1 /g'))"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Hulkke/website-docs
          event-type: ${{ github.repository }}/${{ github.ref_name }}-${{ steps.extract.outputs.sha }}
          client-payload: '{ "repo": "${{ github.repository }}", "ref": "${{ github.ref_name }}", "sha": "${{ github.sha }}" }'
